# Generated by Django 5.0.2 on 2024-03-09 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0002_alter_course_name"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_pay", models.DateField()),
                (
                    "pay_amount",
                    models.PositiveIntegerField(verbose_name="сумма оплаты"),
                ),
                (
                    "pay_method",
                    models.CharField(max_length=25, verbose_name="метод оплаты"),
                ),
                (
                    "paid_course",
                    models.ForeignKey(
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.course",
                        verbose_name="оплаченый курс",
                    ),
                ),
                (
                    "paid_lesson",
                    models.ForeignKey(
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materials.lesson",
                        verbose_name="оплаченый урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
        ),
    ]
