# Generated by Django 5.0.2 on 2024-04-01 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_updatesubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdateSubscription',
            new_name='Subscription',
        ),
    ]
